### ISSUE TITLE
Json parsing

### ISSUE THREAD

**Issue by SeaTurtleManOG** [TommySoucy/MoreCheckmarks#10]
I went to port this for sit, just to successfully port it and find that the mod still errored in the same way it used to

I ported your latest released assuming my custom trader issue would be fixed, unfortunately it was not.

The logs told me about the assort part of the loaddata function was not working.

When loading trader assorts, it expected a JArray, but would get a JObject.

I made a change to the code, it now checks the format of the json, before trying to pass it.

Very simple fix, I hope this can help you, as I've still seen people in your comments in the SPT hub, still have issues.

Changed code:

From:

            LogInfo("\tAssorts");
            JArray assortData = JArray.Parse(RequestHandler.GetJson("/MoreCheckmarksRoutes/assorts"));
            bartersByItemByTrader.Clear();
            for (int i=0; i < assortData.Count; ++i)
            {
                bartersByItemByTrader.Add(new Dictionary<string, List<KeyValuePair<string, int>>>());
                JArray items = assortData[i]["items"] as JArray;
                for (int j = 0; j < items.Count; ++j)
                {
                    if (items[j]["parentId"] != null && items[j]["parentId"].ToString().Equals("hideout"))
                    {
                        JArray barters = assortData[i]["barter_scheme"][items[j]["_id"].ToString()] as JArray;
                        for (int k = 0; k < barters.Count; ++k)
                        {
                            JArray barter = barters[k] as JArray;
                            for (int l = 0; l < barter.Count; ++l)
                            {
                                string priceTPL = barter[l]["_tpl"].ToString();
                                if (!priceTPL.Equals(euro) && !priceTPL.Equals(rouble) && !priceTPL.Equals(dollar))
                                {
                                    if (bartersByItemByTrader[i].TryGetValue(priceTPL, out List<KeyValuePair<string, int>> barterList))
                                    {
                                        barterList.Add(new KeyValuePair<string, int>(items[j]["_tpl"].ToString(), (int)(barter[l]["count"])));
                                    }
                                    else
                                    {
                                        bartersByItemByTrader[i].Add(priceTPL, new List<KeyValuePair<string, int>>() { new KeyValuePair<string, int>(items[j]["_tpl"].ToString(), (int)(barter[l]["count"])) });
                                    }
                                }
                            }
                        }
                    }
                }
            }

To: 

            LogInfo("\tAssorts");
            string jsonAssorts = RequestHandler.GetJson("/MoreCheckmarksRoutes/assorts");

            // Check if the received JSON string is not null or empty
            if (!string.IsNullOrEmpty(jsonAssorts))
            {
                // Attempt to parse the JSON string to determine its format
                try
                {
                    JToken token = JToken.Parse(jsonAssorts);

                    if (token is JArray)
                    {
                        // If the JSON is an array (expected for assorts data)
                        JArray assortData = (JArray)token;
                        bartersByItemByTrader.Clear();

                        for (int i = 0; i < assortData.Count; ++i)
                        {
                            bartersByItemByTrader.Add(new Dictionary<string, List<KeyValuePair<string, int>>>());
                            JArray items = assortData[i]["items"] as JArray;

                            for (int j = 0; j < items.Count; ++j)
                            {
                                if (items[j]["parentId"] != null && items[j]["parentId"].ToString().Equals("hideout"))
                                {
                                    JToken bartersToken = assortData[i]["barter_scheme"][items[j]["_id"].ToString()];

                                    if (bartersToken is JArray)
                                    {
                                        JArray barters = (JArray)bartersToken;

                                        for (int k = 0; k < barters.Count; ++k)
                                        {
                                            JArray barter = barters[k] as JArray;

                                            for (int l = 0; l < barter.Count; ++l)
                                            {
                                                string priceTPL = barter[l]["_tpl"].ToString();

                                                // Check if priceTPL is not a standard currency (euro, rouble, dollar)
                                                if (!priceTPL.Equals(euro) && !priceTPL.Equals(rouble) && !priceTPL.Equals(dollar))
                                                {
                                                    if (bartersByItemByTrader[i].TryGetValue(priceTPL, out List<KeyValuePair<string, int>> barterList))
                                                    {
                                                        barterList.Add(new KeyValuePair<string, int>(items[j]["_tpl"].ToString(), (int)(barter[l]["count"])));
                                                    }
                                                    else
                                                    {
                                                        bartersByItemByTrader[i].Add(priceTPL, new List<KeyValuePair<string, int>>() { new KeyValuePair<string, int>(items[j]["_tpl"].ToString(), (int)(barter[l]["count"])) });
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                    else if (token is JObject)
                    {
                        // Handle the case where the JSON is an object instead of an array
                        LogError("Unexpected JSON format for Assorts: Received an object instead of an array");
                    }
                    else
                    {
                        // Handle other unexpected JSON formats
                        LogError("Unexpected JSON format for Assorts: Unknown format");
                    }
                }
                catch (JsonReaderException ex)
                {
                    LogError("Error parsing Assorts JSON: " + ex.Message);
                }
            }
            else
            {
                // Handle case where JSON string is empty or null
                LogError("No JSON data received for Assorts");
            }

**Comment by TommySoucy** [comment]
Make a pull request if you think its worth it. I haven't looked at your code but I wouldn't be surprised if the SIT database is completely different from SPT-AKI's. I wouldn't expect any of my DB dependent code to work on SIT at all
