### ISSUE TITLE
Items marked as quest items even when already handed in for a quest

### ISSUE THREAD

**Issue by matts1** [TommySoucy/MoreCheckmarks#11]
For example, even after handing in a "fake mustache" to collector, it still shows up as a quest item, like so:
```
Needed (1/1) to complete quest:
  Collector
```

**Comment by TommySoucy** [comment]
The mod doesnt currently check whether an item hand-in condition was fulfilled. I won't be adding that in anytime soon as im busy with other projects. If you feel up to it though, feel free to implement it and make a pull request.

**Comment by matts1** [comment]
I did give it a try, but apparently their servers are overloaded right now so I can't access the documentation easily. I might come back some other time and try again.

**Comment by TommySoucy** [comment]
You wouldnt need any documentation. If you know your way around code a bit, i think this would actually be a singleine fix. Ill put it in here as a note for myself if i get around to fixing this, or if you want to try:

In IsQuestItem, in the Condition foreach loop, youll simply want to add a check for whether the condition has already been fulfilled or not. I dont think im checking this right now for some reason. Condition probably has fulfilled variable ready we could just check
