### ISSUE TITLE
[Feature] Option to lower Brightness/Disable checkmark if item is not FIR

### ISSUE THREAD

**Issue by mutschler** [TommySoucy/MoreCheckmarks#12]
The Checkmark icon will always be displayed. Even if the Item isn't "found in raind" anymore.

An option to enable which will render the checkmark with something like 50% of the brightness or even completely disable it (or use another icon instead... maybe even flip it or something like that) would be nice. Currently it's impossible to tell without looking at the tooltip which items are FIR and could be sold over Flea and which are not.

**Comment by TommySoucy** [comment]
Adding a visual indication specific to FIR items has been on my list, but im not going to be putting any work into MoreCheckmarks anytime soon.

Feel free to implement it yourself and make a pull request
